### ISSUE TITLE
crystal deps won't install shard, asks for github username, password, then "failed to clone"

### ISSUE THREAD

**Issue by vectorselector** [TechMagister/couchdb.cr#2]

**Comment by vectorselector** [comment]
`crystal deps`
strangely asks for a github username, then a password, when attempting to clone this repo for installing the shard.
after entering this info i get an error:
`Failed to clone https://github.com/techmagister/couchdb.git`

**Comment by TechMagister** [comment]
You can try with that url : 
https://github.com/TechMagister/couchdb.cr.git

Pay attention to the project name : **couchdb.cr**

**Comment by vectorselector** [comment]
great! 
adding the shard: 
```
dependencies:
  couchdb:
    github: techmagister/couchdb.cr
```

instead of 
```
dependencies:
  couchdb:
    github: techmagister/couchdb
```

worked fine, and allowed me to reference 
`require "couchdb"`

in my code.

much better than just downloading the git zip and putting it the lib folder manually and having no shard management nor updates nor versioning.

Thank you,
It's a nicer API than what I was doing before using couchdb via the HTTP::Client
