### ISSUE TITLE
sort on find?

### ISSUE THREAD

**Issue by vectorselector** [TechMagister/couchdb.cr#5]
Is it possible to pass a "sort" parameter to a find_document?
for example:
```
  holidays02Query = CouchDB::FindQuery.from_json %({"selector":{"eventMonth":"February"}}, {"sort":{"eventDate":"asc"})
  holidays02 = db.find_document("categories", holidays02Query).docs.not_nil!
```
or 

 ```
 holidays01Query = CouchDB::FindQuery.from_json %({"selector":{"eventMonth":"January"}}, "sort":"eventDate")
  holidays01 = db.find_document("categories", holidays01Query).docs.not_nil!
```
I see in the src, that find_document only expects the selector, but I see that limit works fine

```
  holidays01Query = CouchDB::FindQuery.from_json %({"selector":{"eventMonth":"January"}}, "limit":8)
  holidays01 = db.find_document("categories", holidays01Query).docs.not_nil!
```

skip works fine also, does sort work in some way?

**Comment by TechMagister** [comment]
I havn't the time to develop new features anymore, but feel free to send a PR :)

**Comment by vectorselector** [comment]
Sort works fine already! I should have known, as your JSON.mapping in the find query correctly describes the simpler of the 2 sort formats: the array of strings, vs the array of objects. it looks like:

{"selector":{"field":{"$gte:0}}, "sort":["field"], "limit":8}

OR

{"selector":{"field":{"$gte:0}}, "sort":[{"field":"desc"}, {"field2":"asc"}], "limit":8}

why I was confused was that I wasn't seeing the couchdb error message at first...advising me that it couldn't sort on a non-existing index.

see, 2 things need to be there:
1) is the "field" in the "selector" part, if you want to sort by it, you need to at least list it somehow, easiest being "$gte":0 or "$exists":true ...

2) an INDEX on the couchdb itself!!!

since adding this index was killing all my other queries on the same db, I made a replication locally continually to another database that had the index I wanted for only this special sorted query.

It's kind of like a view, but hopefully the performance is better? it works, anyway
