### ISSUE TITLE
Can you release the current version?

### ISSUE THREAD

**Issue by Schniz** [TechMagister/couchdb.cr#8]
> Yes, it now works for me. However, to be able to merge I would like to see at least one published release and CI builds. See official guidelines on how to create/maintain a shard: https://crystal-lang.org/docs/guides/writing_shards.html
> ...
> 
> @veelenga, https://github.com/veelenga/awesome-crystal/pull/350

Also, I'll try to add CI to a fork of my own, then suggest it as a PR

**Comment by TechMagister** [comment]
I just released v0.1. Thanks for your contributions.

**Comment by Schniz** [comment]
Thanks, and thank you for starting this project 😸
